export const SET_MAILBOXES = 'SET_MAILBOXES'
export const SET_CURRENT_MAILBOX = 'SET_CURRENT_MAILBOX'
export const SET_CURRENT_MAIL = 'SET_CURRENT_MAIL'
export const SET_CURRENT_MAIL_READ = 'SET_CURRENT_MAIL_READ'
